# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # None

builds:
  - main: ./cmd/acct_etl/acct_etl.go
    id: "acct_etl"
    binary: acct_etl
    goos:
      - linux
      - darwin
      - windows
      - freebsd

  - main: ./cmd/feeder/feeder.go
    id: "feeder"
    binary: feeder
    goos:
      - linux
      - darwin
      - windows
      - freebsd

  - main: ./cmd/tracker/tracker.go
    id: "tracker"
    binary: tracker
    goos:
      - linux
      - darwin
      - windows
      - freebsd

  - main: ./cmd/wrapper/wrapper.go
    id: "wrapper"
    binary: wrapper
    goos:
      - linux
      - darwin
      - windows
      - freebsd

  - main: ./cmd/linktool/linktool.go
    id: "linktool"
    binary: linktool
    goos:
      - linux
      - darwin
      - windows
      - freebsd

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
